#!/usr/bin/env python3
"""Generate Chip 1 East Asian Width W/F and Mn/Me tables (ADR 0035 D2).

Humans do not edit crates/vt-engine/src/east_asian_width.rs. Run this script
and commit the output. The Unicode version must match third_party/unicode.pin.

`--check` verifies the committed file against the pin. When the host Python's
unicodedata matches the pin, it also regenerates and compares byte-for-byte.
When it does not (e.g. ubuntu-latest ships Unicode 15.0.0), the pin's
east_asian_width_sha256 and the file header must still match — skip is a failure.
"""
from __future__ import annotations

import hashlib
import pathlib
import sys
import unicodedata

ROOT = pathlib.Path(__file__).resolve().parents[1]
PIN_PATH = ROOT / "third_party" / "unicode.pin"
OUT_PATH = ROOT / "crates" / "vt-engine" / "src" / "east_asian_width.rs"


def pin_fields() -> dict[str, str]:
    out: dict[str, str] = {}
    for line in PIN_PATH.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.lstrip().startswith("#"):
            key, val = line.split("=", 1)
            out[key.strip()] = val.strip()
    if "unidata_version" not in out:
        raise SystemExit(f"{PIN_PATH}: missing unidata_version")
    return out


def write_pin_sha256(digest: str) -> None:
    lines = PIN_PATH.read_text(encoding="utf-8").splitlines()
    key = "east_asian_width_sha256"
    replaced = False
    out: list[str] = []
    for line in lines:
        if line.startswith(f"{key} "):
            out.append(f"{key} = {digest}")
            replaced = True
        else:
            out.append(line)
    if not replaced:
        out.append(f"{key} = {digest}")
    PIN_PATH.write_text("\n".join(out) + "\n", encoding="utf-8")


def file_sha256(path: pathlib.Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def header_version(body: str) -> str | None:
    for line in body.splitlines()[:4]:
        if line.startswith("// Unicode ") and " via Python" in line:
            return line.removeprefix("// Unicode ").split(" via Python", 1)[0].strip()
    return None


def ranges_of(predicate) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = None
    prev = None
    for cp in range(0x110000):
        if predicate(cp):
            if start is None:
                start = prev = cp
            elif cp == prev + 1:
                prev = cp
            else:
                out.append((start, prev))
                start = prev = cp
        elif start is not None:
            out.append((start, prev))
            start = prev = None
    if start is not None:
        out.append((start, prev))
    return out


def is_wide(cp: int) -> bool:
    try:
        c = chr(cp)
    except ValueError:
        return False
    return unicodedata.east_asian_width(c) in ("W", "F")


def is_mark(cp: int) -> bool:
    try:
        c = chr(cp)
    except ValueError:
        return False
    return unicodedata.category(c) in ("Mn", "Me")


def emit_ranges(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [f"const {name}: &[(u32, u32)] = &["]
    for lo, hi in ranges:
        lines.append(f"    (0x{lo:X}, 0x{hi:X}),")
    lines.append("];")
    return "\n".join(lines)


def generated_source(pin: str, wide: list[tuple[int, int]], marks: list[tuple[int, int]]) -> str:
    return f"""// @generated by scripts/gen-east-asian-width.py. DO NOT EDIT.
// Unicode {pin} via Python unicodedata (ADR 0035 D2).
// W/F → 2 columns; Mn/Me cluster. Ambiguous is not in WIDE_RANGES.

{emit_ranges("WIDE_RANGES", wide)}

{emit_ranges("MARK_RANGES", marks)}

fn contains(ranges: &[(u32, u32)], cp: u32) -> bool {{
    ranges
        .binary_search_by(|&(lo, hi)| {{
            if hi < cp {{
                core::cmp::Ordering::Less
            }} else if lo > cp {{
                core::cmp::Ordering::Greater
            }} else {{
                core::cmp::Ordering::Equal
            }}
        }})
        .is_ok()
}}

/// East Asian Width Wide or Fullwidth (UAX #11). Ambiguous is false.
pub(crate) fn is_wide(cp: u32) -> bool {{
    contains(WIDE_RANGES, cp)
}}

/// Unicode categories Mn (nonspacing) and Me (enclosing).
pub(crate) fn is_mark(cp: u32) -> bool {{
    contains(MARK_RANGES, cp)
}}
"""


def check_committed(pin: str, expected_sha: str | None) -> int:
    if not OUT_PATH.is_file():
        print(
            f"missing {OUT_PATH.relative_to(ROOT)} (ADR 0035 D2)",
            file=sys.stderr,
        )
        return 1
    existing = OUT_PATH.read_text(encoding="utf-8")
    hdr = header_version(existing)
    if hdr != pin:
        print(
            f"{OUT_PATH.relative_to(ROOT)} header is Unicode {hdr!r}, "
            f"pin is {pin!r} ({PIN_PATH.relative_to(ROOT)})",
            file=sys.stderr,
        )
        return 1
    if not expected_sha:
        print(
            f"{PIN_PATH.relative_to(ROOT)}: missing east_asian_width_sha256 "
            "(required when host unicodedata may differ from pin)",
            file=sys.stderr,
        )
        return 1
    got_sha = file_sha256(OUT_PATH)
    if got_sha != expected_sha:
        print(
            f"{OUT_PATH.relative_to(ROOT)} sha256 is {got_sha}, "
            f"pin is {expected_sha}. Re-run scripts/gen-east-asian-width.py "
            "with a matching Python and commit the output + pin.",
            file=sys.stderr,
        )
        return 1
    return 0


def main() -> int:
    check = "--check" in sys.argv
    fields = pin_fields()
    pin = fields["unidata_version"]
    expected_sha = fields.get("east_asian_width_sha256")
    got_ucd = unicodedata.unidata_version

    if check:
        rc = check_committed(pin, expected_sha)
        if rc != 0:
            return rc
        if got_ucd != pin:
            print(
                f"ok: {OUT_PATH.relative_to(ROOT)} matches pin sha256 "
                f"(host unicodedata {got_ucd}, pin {pin})"
            )
            return 0
        wide = ranges_of(is_wide)
        marks = ranges_of(is_mark)
        body = generated_source(pin, wide, marks)
        existing = OUT_PATH.read_text(encoding="utf-8")
        if existing != body:
            print(
                f"{OUT_PATH.relative_to(ROOT)} differs from generator output "
                "(ADR 0035 D2). Re-run scripts/gen-east-asian-width.py and commit.",
                file=sys.stderr,
            )
            return 1
        print(f"ok: {OUT_PATH.relative_to(ROOT)} matches Unicode {pin}")
        return 0

    if got_ucd != pin:
        print(
            f"unicodedata.unidata_version is {got_ucd}, pin is {pin} "
            f"({PIN_PATH}). Bump the pin in its own PR or use a Python "
            "whose UCD matches. Skip is a failure (ADR 0002 D5).",
            file=sys.stderr,
        )
        return 1

    wide = ranges_of(is_wide)
    marks = ranges_of(is_mark)
    body = generated_source(pin, wide, marks)
    OUT_PATH.write_text(body, encoding="utf-8")
    digest = hashlib.sha256(body.encode()).hexdigest()
    write_pin_sha256(digest)
    print(f"wrote {OUT_PATH.relative_to(ROOT)} Unicode {pin}")
    print(f"  WIDE_RANGES {len(wide)}  MARK_RANGES {len(marks)}")
    print(f"  east_asian_width_sha256 {digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
